[package]
name = "alipay"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11", features = ["json", "multipart"] }

# 日期支持
chrono = { version = "0.4", features = ["serde"] }

# log
# log = "0.4"
# fast_log="1.3"

# json
serde = {version = "1", features = ["derive"]}
serde_json = "1"

thiserror = "1.0"

openssl = "0.10"

md-5 = "0.9.1"
hex = "0.4.3"