[package]
name = "alipay-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

exclude = [
    "examples/*"
]

[dependencies]
ureq = { version = "2", features = ["json", "charset"] }

# datetime
chrono = { version = "0.4", features = ["serde"] }

# json
serde = {version = "1", features = ["derive"]}
serde_json = "1"

thiserror = "1.0"

openssl = "0.10"

md-5 = "0.9.1"
hex = "0.4.3"

serde_urlencoded = "0.7"

alipay_derive = {path = "./src/alipay_derive"}