[package]
name = "alipay_params"
version = "0.1.0"
edition = "2021"
authors = ["chy <343938938@qq.com>"]
license = "MIT/Apache-2.0"
description = "alipay-rs params"

[lib]
path = "src/lib.rs"

[dependencies]
alipay_macros = "0.1"
